//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplicationTemplate {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ConsoleApplicationTemplate.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MMPrompt {
            get {
                return ResourceManager.GetString("MMPrompt", resourceCulture);
            }
        }
        
        internal static string MMOption1 {
            get {
                return ResourceManager.GetString("MMOption1", resourceCulture);
            }
        }
        
        internal static string MMOption2 {
            get {
                return ResourceManager.GetString("MMOption2", resourceCulture);
            }
        }
        
        internal static string MMOption3 {
            get {
                return ResourceManager.GetString("MMOption3", resourceCulture);
            }
        }
        
        internal static string SM1Prompt {
            get {
                return ResourceManager.GetString("SM1Prompt", resourceCulture);
            }
        }
        
        internal static string SM1Option1 {
            get {
                return ResourceManager.GetString("SM1Option1", resourceCulture);
            }
        }
        
        internal static string SM1Option2 {
            get {
                return ResourceManager.GetString("SM1Option2", resourceCulture);
            }
        }
    }
}
